AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectId:
    Type: String
  DatabaseInstanceType:
    Type: String
    Description: The instance type to use for the database.
  DBName:
    Type: String
  DBUser:
    Type: String
  DBPassword:
    Type: String
    NoEcho: true
  DBSGStack:
    Type: String
    AllowedPattern: '[A-Za-z][A-Za-z0-9-]{0,127}'
  SGStack:
    Type: String

Resources:
  DB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: !Ref DatabaseInstanceType
      Engine: MySQL
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBSubnetGroupName:
        Fn::ImportValue: !Sub ${DBSGStack}::SubnetGroupData
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${SGStack}::DBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectId}-DB-Instance
        - Key: Billing
          Value: !Ref ProjectId
Outputs:
  EndpointAddress:
    Description: DB endpoint address
    Value: !GetAtt DB.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}::EndpointAddress